/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description ## Description
         *
         *     This route is used to authenticate users and generate a session ID stored in a cookie named "session," allowing authorized access to perform various operations within the panel.
         *
         *     ## Note
         *
         *     - Retrieve the generated session ID from the cookie named "session".
         *
         *     - Ensure the provided credentials (`username` and `password`) are correct for successful authentication.
         *
         *     - Handle any potential errors or failure messages returned in the response.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/panel/api/inbounds/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Inbounds
         * @description ## Description
         *
         *     This route is used to retrieve a comprehensive list of all inbounds along with their associated client options and statistics.
         *
         *     ## Note
         *
         *     - Requires a valid session ID (from the login endpoint), Include the session ID stored in the cookie named "session" for authorization.
         *
         *     - If no inbounds are available, the response will contain an empty array `[]`.
         *
         *     - Handle any potential errors or failure messages returned in the response.
         */
        get: operations["inbounds"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/panel/api/inbounds/get/{inboundId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                inboundId: string;
            };
            cookie?: never;
        };
        /**
         * Inbound
         * @description ## Description
         *
         *     This route is used to retrieve statistics and details for a specific inbound connection identified by `{inboundId}`. This includes information about the inbound itself, its statistics, and the clients connected to it.
         *
         *     ## **Path Parameter**
         *
         *     - `{inboundId}`: Identifier of the specific inbound for which information is requested.
         *
         *
         *     ## Note
         *
         *     - Requires a valid session ID (from the login endpoint), Include the session ID stored in the cookie named "session" for authorization.
         *
         *     - Ensure that the provided `{inboundId}` corresponds to an existing inbound within the system.
         *
         *     - Handle any potential errors or failure messages returned in the response.
         */
        get: operations["inbound"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/panel/api/inbounds/getClientTraffics/{email}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                email: string;
            };
            cookie?: never;
        };
        /**
         * Client Traffics with email
         * @description ## Description
         *
         *     This route is used to retrieve information about a specific client based on their email. This endpoint provides details such as traffic statistics and other relevant information related to the client.
         *
         *     ## **Path Parameter**
         *
         *     - `{email}`: Email address of the client for whom information is requested.
         *
         *
         *     ## **Note**
         *
         *     - Requires a valid session ID (from the login endpoint), Include the session ID stored in the cookie named "session" for authorization.
         *
         *     - Ensure that the provided `{email}` corresponds to a valid client in the system to retrieve accurate information.
         *     - Handle any potential errors or failure messages returned in the response.
         */
        get: operations["clientTrafficsWithEmail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/panel/api/inbounds/getClientTrafficsById/{uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        /**
         * Client Traffics with ID
         * @description ## Description
         *
         *     This route is used to retrieve information about a specific client based on their email. This endpoint provides details such as traffic statistics and other relevant information related to the client.
         *
         *     ## **Path Parameter**
         *
         *     - `{email}`: Email address of the client for whom information is requested.
         *
         *
         *     ## **Note**
         *
         *     - Requires a valid session ID (from the login endpoint), Include the session ID stored in the cookie named "session" for authorization.
         *
         *     - Ensure that the provided `{email}` corresponds to a valid client in the system to retrieve accurate information.
         *     - Handle any potential errors or failure messages returned in the response.
         */
        get: operations["clientTrafficsWithId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/panel/api/inbounds/createbackup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * tgbot - sends backup to admins
         * @description ## Description
         *
         *     This endpoint triggers the creation of a system backup and initiates the delivery of the backup file to designated administrators via a configured Telegram bot. The server verifies the Telegram bot's activation status within the system settings and checks for the presence of admin IDs specified in the settings before sending the backup.
         *
         *     ## Note
         *
         *     - Requires a valid session ID (from the login endpoint). Include the session ID stored in the cookie named "session" for authorization.
         *
         *     - Upon implementation, the backup file might be sent through the Telegram bot registered in the panel settings.
         *
         *     - Handle any potential errors or failure messages returned in the response.
         */
        get: operations["tgbotSendsBackupToAdmins"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/panel/api/inbounds/clientIps/{email}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                email: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Client Ip address
         * @description ## Description
         *
         *     This route is used to retrieve the IP records associated with a specific client identified by their email.
         *
         *     ## Path Parameter
         *
         *     - **`{email}`** : Email address of the client for whom IP records are requested.
         *
         *
         *     ## Note
         *
         *     - Requires a valid session ID (from the login endpoint), Include the session ID stored in the cookie named "session" for authorization.
         *
         *     - Ensure that the provided `{email}` corresponds to a valid client in the system to retrieve accurate IP records.
         *     - Handle any potential errors or failure messages returned in the response.
         */
        post: operations["clientIpAddress"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/panel/api/inbounds/add": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Inbound
         * @description ## Description
         *
         *     This route is used to add a new inbound configuration.
         *
         *     ## Note
         *
         *     - Requires a valid session ID (from the login endpoint), Include the session ID stored in the cookie named "session" for authorization.
         *
         *     - Ensure the provided inbound configuration parameters are correct to add the inbound successfully.
         *     - Ensure that sub-arrays or objects within the JSON body are stringified in JSON format for correct parsing by the panel.
         *     - Handle any potential errors or failure messages returned in the response.
         */
        post: operations["addInbound"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/panel/api/inbounds/addClient": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Client to inbound
         * @description ## Description
         *
         *     This route is used to add a new client to a specific inbound identified by its ID.
         *
         *     ## Note
         *
         *     - Requires a valid session ID (from the login endpoint), Include the session ID stored in the cookie named "session" for authorization.
         *
         *     - Verify that the provided inbound ID (`id`) corresponds to an existing inbound within the system.
         *     - Format the client information in the `settings` parameter as a stringified JSON format within the request body.
         *     - Handle any potential errors or failure messages returned in the response.
         */
        post: operations["addClientToInbound"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/panel/api/inbounds/update/{inboundId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                inboundId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Update Inbound
         * @description ## Description
         *
         *     This route is used to update an existing inbound identified by its ID (`{inboundId}`).
         *
         *     ## **Path Parameter**
         *
         *     - `{inboundId}`: Identifier of the specific inbound to be updated.
         *
         *
         *     ## Note
         *
         *     - Requires a valid session ID (from the login endpoint), Include the session ID stored in the cookie named "session" for authorization.
         *
         *     - Verify that the provided `{inboundId}` corresponds to an existing inbound within the system.
         *     - Ensure that sub-arrays or objects within the JSON body are stringified in JSON format for correct parsing by the panel.
         *     - Handle any potential errors or failure messages returned in the response.
         */
        post: operations["updateInbound"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/panel/api/inbounds/updateClient/{uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Update Client
         * @description ## Description
         *
         *     This route is used to update an existing client identified by its UUID (`{uuid}`) within a specific inbound.
         *
         *     ## **Path Parameter**
         *
         *     - `{uuid}` : Unique identifier (UUID) of the specific client for whom information is being updated.
         *
         *
         *     ## Note
         *
         *     - Requires a valid session ID (from the login endpoint). Include the session ID stored in the cookie named "session" for authorization.
         *
         *     - Verify that the provided `{uuid}` corresponds to an existing client within the system associated with the specified inbound.
         *     - Format the client information in the `settings` parameter as a stringified JSON format within the request body.
         *     - Handle any potential errors or failure messages returned in the response.
         */
        post: operations["updateClient"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/panel/api/inbounds/clearClientIps/{email}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                email: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Clear Client Ip address
         * @description ## Description
         *
         *     This route is used to reset or clear the IP records associated with a specific client identified by their email address (`{email}`).
         *
         *     ## Path Parameter
         *
         *     - `{email}` : Email address of the client for whom IP records need to be reset.
         *
         *
         *     ## Note
         *
         *     - Requires a valid session ID (from the login endpoint). Include the session ID stored in the cookie named "session" for authorization.
         *
         *     - Verify that the provided `{email}` corresponds to an existing client within the system for whom IP records need to be cleared.
         *     - Handle any potential errors or failure messages returned in the response.
         */
        post: operations["clearClientIpAddress"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/panel/api/inbounds/resetAllTraffics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset traffics of all inbounds
         * @description ## Description
         *
         *     This route is used to reset the traffic statistics for all inbounds within the system.
         *
         *     ## Note
         *
         *     - Requires a valid session ID (from the login endpoint). Include the session ID stored in the cookie named "session" for authorization.
         *
         *     - Resetting the traffics through this endpoint affects the statistics for all inbounds within the system.
         *     - Handle any potential errors or failure messages returned in the response.
         */
        post: operations["resetTrafficsOfAllInbounds"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/panel/api/inbounds/resetAllClientTraffics/{inboundId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                inboundId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset traffics of all clients in an inbound
         * @description ## Description
         *
         *     This route is used to reset the traffic statistics for all clients associated with a specific inbound identified by its ID (`{inboundId}`).
         *
         *     ## Path Parameter
         *
         *     - `{inboundId}` : Identifier of the specific inbound for which client traffics are being reset.
         *
         *
         *     ## Note
         *
         *     - Requires a valid session ID (from the login endpoint). Include the session ID stored in the cookie named "session" for authorization.
         *
         *     - Resetting the client traffics through this endpoint affects all clients associated with the specified inbound.
         *     - Verify that the provided `{inboundId}` corresponds to an existing inbound within the system.
         *     - Handle any potential errors or failure messages returned in the response.
         */
        post: operations["resetTrafficsOfAllClientsInAnInbound"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/panel/api/inbounds/{inboundId}/resetClientTraffic/{email}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                inboundId: string;
                email: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset Client Traffic
         * @description ## Description
         *
         *     This route is used to reset the traffic statistics for a specific client identified by their email address (`{email}`) within a particular inbound identified by its ID (`{inboundId}`).
         *
         *     ## Path Parameters
         *
         *     - `{inboundId}` : Identifier of the specific inbound where the client belongs.
         *     - `{email}` : Email address of the client for whom traffic statistics are being reset.
         *
         *
         *     ## Note
         *
         *     - Requires a valid session ID (from the login endpoint). Include the session ID stored in the cookie named "session" for authorization.
         *
         *     - Resetting the client traffic through this endpoint affects the statistics for the specified client within the specified inbound.
         *     - Verify that the provided {inboundId} corresponds to an existing inbound and `{email}` corresponds to an existing client within the system.
         *     - Handle any potential errors or failure messages returned in the response.
         */
        post: operations["resetClientTraffic"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/panel/api/inbounds/{inboundId}/delClient/{uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                inboundId: string;
                uuid: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Delete Client
         * @description ## Description
         *
         *     This route is used to delete a client identified by its UUID (`{uuid}`) within a specific inbound identified by its ID (`{inboundId}`).
         *
         *     ## Path Parameters
         *
         *     - `{inboundId}` : Identifier of the specific inbound from which the client will be deleted.
         *     - `{uuid}` : Unique identifier (UUID) of the specific client to be deleted.
         *
         *
         *     ## Note
         *
         *     - Requires a valid session ID (from the login endpoint). Include the session ID stored in the cookie named "session" for authorization.
         *
         *     - Ensure that the provided `{inboundId}` corresponds to an existing inbound and `{uuid}` corresponds to an existing client within the system.
         *     - Deleting the client through this endpoint permanently removes the specified client from the specified inbound.
         *     - Handle any potential errors or failure messages returned in the response.
         */
        post: operations["deleteClient"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/panel/api/inbounds/del/{inboundId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                inboundId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Delete Inbound
         * @description ## Description
         *
         *     This route is used to delete an inbound identified by its ID (`{inboundId}`).
         *
         *     ## Path Parameter
         *
         *     - `{inboundId}` : Identifier of the specific inbound to be deleted.
         *
         *
         *     ## Note
         *
         *     - Requires a valid session ID (from the login endpoint). Include the session ID stored in the cookie named "session" for authorization.
         *
         *     - Ensure that the provided `{inboundId}` corresponds to an existing inbound within the system.
         *     - Deleting the inbound through this endpoint permanently removes the specified inbound.
         *     - Handle any potential errors or failure messages returned in the response.
         */
        post: operations["deleteInbound"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/panel/api/inbounds/delDepletedClients/{inboundId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                inboundId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Delete Depleted Clients
         * @description ## Description
         *
         *     This route is used to delete all depleted clients associated with a specific inbound identified by its ID (`{inboundId}`). If no `{inboundId}` is specified, depleted clients will be deleted from all inbounds.
         *
         *     ## Path Parameter
         *
         *     - `{inboundId}` : Identifier of the specific inbound from which the depleted clients will be deleted. If not specified, depleted clients will be deleted from all inbounds.
         *
         *
         *     ## Note
         *
         *     - Requires a valid session ID (from the login endpoint). Include the session ID stored in the cookie named "session" for authorization.
         *
         *     - If `{inboundId}` is provided, ensure it corresponds to an existing inbound within the system. If not provided, depleted clients will be deleted from all inbounds.
         *     - Deleting depleted clients through this endpoint permanently removes all depleted clients from the specified inbound(s).
         *     - Handle any potential errors or failure messages returned in the response.
         */
        post: operations["deleteDepletedClients"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/panel/api/inbounds/onlines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Online Clients
         * @description Online Clients
         */
        post: operations["onlineClients"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/x-www-form-urlencoded": {
                    /** @example admin */
                    password?: string;
                    /** @example admin */
                    username?: string;
                };
            };
        };
        responses: {
            /** @description Login / Failed */
            200: {
                headers: {
                    "Content-Encoding"?: string;
                    "Content-Length"?: string;
                    Date?: string;
                    Vary?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Login Successfully */
                        msg?: string;
                        /** @example null */
                        obj?: unknown;
                        /** @example true */
                        success?: boolean;
                    };
                };
            };
        };
    };
    inbounds: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Inbounds / No Inbounds */
            200: {
                headers: {
                    "Content-Encoding"?: string;
                    "Content-Length"?: string;
                    Date?: string;
                    Vary?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example  */
                        msg?: string;
                        /** @example [
                         *       {
                         *         "allocate": "{\n  \"strategy\": \"always\",\n  \"refresh\": 5,\n  \"concurrency\": 3\n}",
                         *         "clientStats": [
                         *           {
                         *             "down": 0,
                         *             "email": "hyvcs325",
                         *             "enable": true,
                         *             "expiryTime": 0,
                         *             "id": 3,
                         *             "inboundId": 3,
                         *             "reset": 0,
                         *             "total": 0,
                         *             "up": 0
                         *           },
                         *           {
                         *             "down": 0,
                         *             "email": "27225ost",
                         *             "enable": true,
                         *             "expiryTime": 0,
                         *             "id": 5,
                         *             "inboundId": 3,
                         *             "reset": 0,
                         *             "total": 0,
                         *             "up": 0
                         *           }
                         *         ],
                         *         "down": 0,
                         *         "enable": true,
                         *         "expiryTime": 0,
                         *         "id": 3,
                         *         "listen": "",
                         *         "port": 37155,
                         *         "protocol": "vless",
                         *         "remark": "",
                         *         "settings": "{\n  \"clients\": [\n    {\n      \"email\": \"hyvcs325\",\n      \"enable\": true,\n      \"expiryTime\": 0,\n      \"flow\": \"\",\n      \"id\": \"819920c0-22c8-4c83-8713-9c3da4980396\",\n      \"limitIp\": 0,\n      \"reset\": 0,\n      \"subId\": \"jmrwimzhicxm7hrm\",\n      \"tgId\": \"\",\n      \"totalGB\": 0\n    },\n    {\n      \"email\": \"27225ost\",\n      \"enable\": true,\n      \"expiryTime\": 0,\n      \"flow\": \"\",\n      \"id\": \"bf036995-a81d-41b3-8e06-8e233418c96a\",\n      \"limitIp\": 0,\n      \"reset\": 0,\n      \"subId\": \"jw45dtw6rhvefikz\",\n      \"tgId\": \"\",\n      \"totalGB\": 0\n    }\n  ],\n  \"decryption\": \"none\",\n  \"fallbacks\": []\n}",
                         *         "sniffing": "{\n  \"enabled\": false,\n  \"destOverride\": [\n    \"http\",\n    \"tls\",\n    \"quic\",\n    \"fakedns\"\n  ],\n  \"metadataOnly\": false,\n  \"routeOnly\": false\n}",
                         *         "streamSettings": "{\n  \"network\": \"tcp\",\n  \"security\": \"reality\",\n  \"externalProxy\": [],\n  \"realitySettings\": {\n    \"show\": false,\n    \"xver\": 0,\n    \"dest\": \"yahoo.com:443\",\n    \"serverNames\": [\n      \"yahoo.com\",\n      \"www.yahoo.com\"\n    ],\n    \"privateKey\": \"QJS9AerMmDU-DrTe_SAL7vX6_2wg19OxCuthZLLs40g\",\n    \"minClient\": \"\",\n    \"maxClient\": \"\",\n    \"maxTimediff\": 0,\n    \"shortIds\": [\n      \"97de\",\n      \"5f7b4df7d0605151\",\n      \"cc1a7d15c439\",\n      \"f196851a\",\n      \"e291c2\",\n      \"b10c0deeceec08\",\n      \"19\",\n      \"7db6c63a5d\"\n    ],\n    \"settings\": {\n      \"publicKey\": \"UNXIILQ_LpbZdXGbhNCMele1gaPVIfCJ9N0AoLYdRUE\",\n      \"fingerprint\": \"random\",\n      \"serverName\": \"\",\n      \"spiderX\": \"/\"\n    }\n  },\n  \"tcpSettings\": {\n    \"acceptProxyProtocol\": false,\n    \"header\": {\n      \"type\": \"none\"\n    }\n  }\n}",
                         *         "tag": "inbound-37155",
                         *         "total": 0,
                         *         "up": 0
                         *       },
                         *       {
                         *         "allocate": "{\n  \"strategy\": \"always\",\n  \"refresh\": 5,\n  \"concurrency\": 3\n}",
                         *         "clientStats": [
                         *           {
                         *             "down": 0,
                         *             "email": "s729v2km",
                         *             "enable": true,
                         *             "expiryTime": 0,
                         *             "id": 4,
                         *             "inboundId": 4,
                         *             "reset": 0,
                         *             "total": 0,
                         *             "up": 0
                         *           }
                         *         ],
                         *         "down": 0,
                         *         "enable": true,
                         *         "expiryTime": 0,
                         *         "id": 4,
                         *         "listen": "",
                         *         "port": 44360,
                         *         "protocol": "vless",
                         *         "remark": "",
                         *         "settings": "{\n  \"clients\": [\n    {\n      \"id\": \"a39c9655-bcbb-43c4-9b3b-ebd8b7ae9e1e\",\n      \"flow\": \"\",\n      \"email\": \"s729v2km\",\n      \"limitIp\": 0,\n      \"totalGB\": 0,\n      \"expiryTime\": 0,\n      \"enable\": true,\n      \"tgId\": \"\",\n      \"subId\": \"n2b9ubaioe06cak8\",\n      \"reset\": 0\n    }\n  ],\n  \"decryption\": \"none\",\n  \"fallbacks\": []\n}",
                         *         "sniffing": "{\n  \"enabled\": false,\n  \"destOverride\": [\n    \"http\",\n    \"tls\",\n    \"quic\",\n    \"fakedns\"\n  ],\n  \"metadataOnly\": false,\n  \"routeOnly\": false\n}",
                         *         "streamSettings": "{\n  \"network\": \"tcp\",\n  \"security\": \"none\",\n  \"externalProxy\": [],\n  \"tcpSettings\": {\n    \"acceptProxyProtocol\": false,\n    \"header\": {\n      \"type\": \"none\"\n    }\n  }\n}",
                         *         "tag": "inbound-44360",
                         *         "total": 0,
                         *         "up": 0
                         *       }
                         *     ] */
                        obj?: {
                            /** @example {
                             *       "strategy": "always",
                             *       "refresh": 5,
                             *       "concurrency": 3
                             *     } */
                            allocate?: string;
                            /** @example [
                             *       {
                             *         "down": 0,
                             *         "email": "hyvcs325",
                             *         "enable": true,
                             *         "expiryTime": 0,
                             *         "id": 3,
                             *         "inboundId": 3,
                             *         "reset": 0,
                             *         "total": 0,
                             *         "up": 0
                             *       },
                             *       {
                             *         "down": 0,
                             *         "email": "27225ost",
                             *         "enable": true,
                             *         "expiryTime": 0,
                             *         "id": 5,
                             *         "inboundId": 3,
                             *         "reset": 0,
                             *         "total": 0,
                             *         "up": 0
                             *       }
                             *     ] */
                            clientStats?: {
                                /** @example 0 */
                                down?: number;
                                /** @example hyvcs325 */
                                email?: string;
                                /** @example true */
                                enable?: boolean;
                                /** @example 0 */
                                expiryTime?: number;
                                /** @example 3 */
                                id?: number;
                                /** @example 3 */
                                inboundId?: number;
                                /** @example 0 */
                                reset?: number;
                                /** @example 0 */
                                total?: number;
                                /** @example 0 */
                                up?: number;
                            }[];
                            /** @example 0 */
                            down?: number;
                            /** @example true */
                            enable?: boolean;
                            /** @example 0 */
                            expiryTime?: number;
                            /** @example 3 */
                            id?: number;
                            /** @example  */
                            listen?: string;
                            /** @example 37155 */
                            port?: number;
                            /** @example vless */
                            protocol?: string;
                            /** @example  */
                            remark?: string;
                            /** @example {
                             *       "clients": [
                             *         {
                             *           "email": "hyvcs325",
                             *           "enable": true,
                             *           "expiryTime": 0,
                             *           "flow": "",
                             *           "id": "819920c0-22c8-4c83-8713-9c3da4980396",
                             *           "limitIp": 0,
                             *           "reset": 0,
                             *           "subId": "jmrwimzhicxm7hrm",
                             *           "tgId": "",
                             *           "totalGB": 0
                             *         },
                             *         {
                             *           "email": "27225ost",
                             *           "enable": true,
                             *           "expiryTime": 0,
                             *           "flow": "",
                             *           "id": "bf036995-a81d-41b3-8e06-8e233418c96a",
                             *           "limitIp": 0,
                             *           "reset": 0,
                             *           "subId": "jw45dtw6rhvefikz",
                             *           "tgId": "",
                             *           "totalGB": 0
                             *         }
                             *       ],
                             *       "decryption": "none",
                             *       "fallbacks": []
                             *     } */
                            settings?: string;
                            /** @example {
                             *       "enabled": false,
                             *       "destOverride": [
                             *         "http",
                             *         "tls",
                             *         "quic",
                             *         "fakedns"
                             *       ],
                             *       "metadataOnly": false,
                             *       "routeOnly": false
                             *     } */
                            sniffing?: string;
                            /** @example {
                             *       "network": "tcp",
                             *       "security": "reality",
                             *       "externalProxy": [],
                             *       "realitySettings": {
                             *         "show": false,
                             *         "xver": 0,
                             *         "dest": "yahoo.com:443",
                             *         "serverNames": [
                             *           "yahoo.com",
                             *           "www.yahoo.com"
                             *         ],
                             *         "privateKey": "QJS9AerMmDU-DrTe_SAL7vX6_2wg19OxCuthZLLs40g",
                             *         "minClient": "",
                             *         "maxClient": "",
                             *         "maxTimediff": 0,
                             *         "shortIds": [
                             *           "97de",
                             *           "5f7b4df7d0605151",
                             *           "cc1a7d15c439",
                             *           "f196851a",
                             *           "e291c2",
                             *           "b10c0deeceec08",
                             *           "19",
                             *           "7db6c63a5d"
                             *         ],
                             *         "settings": {
                             *           "publicKey": "UNXIILQ_LpbZdXGbhNCMele1gaPVIfCJ9N0AoLYdRUE",
                             *           "fingerprint": "random",
                             *           "serverName": "",
                             *           "spiderX": "/"
                             *         }
                             *       },
                             *       "tcpSettings": {
                             *         "acceptProxyProtocol": false,
                             *         "header": {
                             *           "type": "none"
                             *         }
                             *       }
                             *     } */
                            streamSettings?: string;
                            /** @example inbound-37155 */
                            tag?: string;
                            /** @example 0 */
                            total?: number;
                            /** @example 0 */
                            up?: number;
                        }[];
                        /** @example true */
                        success?: boolean;
                    };
                };
            };
        };
    };
    inbound: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                inboundId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful / Failed */
            200: {
                headers: {
                    "Content-Encoding"?: string;
                    "Content-Length"?: string;
                    Date?: string;
                    Vary?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example  */
                        msg?: string;
                        obj?: {
                            /** @example {
                             *       "strategy": "always",
                             *       "refresh": 5,
                             *       "concurrency": 3
                             *     } */
                            allocate?: string;
                            /** @example null */
                            clientStats?: unknown;
                            /** @example 0 */
                            down?: number;
                            /** @example true */
                            enable?: boolean;
                            /** @example 0 */
                            expiryTime?: number;
                            /** @example 2 */
                            id?: number;
                            /** @example  */
                            listen?: string;
                            /** @example 38476 */
                            port?: number;
                            /** @example vless */
                            protocol?: string;
                            /** @example  */
                            remark?: string;
                            /** @example {
                             *       "clients": [
                             *         {
                             *           "id": "7da4dd82-66e6-4dfa-a66b-bf423f5407ea",
                             *           "flow": "",
                             *           "email": "t6l5ljc9",
                             *           "limitIp": 0,
                             *           "totalGB": 0,
                             *           "expiryTime": 0,
                             *           "enable": true,
                             *           "tgId": "",
                             *           "subId": "ile0ixxgdmjeuz5m",
                             *           "reset": 0
                             *         }
                             *       ],
                             *       "decryption": "none",
                             *       "fallbacks": []
                             *     } */
                            settings?: string;
                            /** @example {
                             *       "enabled": false,
                             *       "destOverride": [
                             *         "http",
                             *         "tls",
                             *         "quic",
                             *         "fakedns"
                             *       ],
                             *       "metadataOnly": false,
                             *       "routeOnly": false
                             *     } */
                            sniffing?: string;
                            /** @example {
                             *       "network": "tcp",
                             *       "security": "reality",
                             *       "externalProxy": [],
                             *       "realitySettings": {
                             *         "show": false,
                             *         "xver": 0,
                             *         "dest": "yahoo.com:443",
                             *         "serverNames": [
                             *           "yahoo.com",
                             *           "www.yahoo.com"
                             *         ],
                             *         "privateKey": "yKUjT7SgfQH8fOTqsKLhwkOWiqRi5oC0Y4lFZXb0CTE",
                             *         "minClient": "",
                             *         "maxClient": "",
                             *         "maxTimediff": 0,
                             *         "shortIds": [
                             *           "8714e8f78bd9",
                             *           "8692",
                             *           "4e",
                             *           "9c46e1",
                             *           "52c0f48e",
                             *           "2d439ce7fd35bd",
                             *           "a64d2fc4a1",
                             *           "2520ce66461ba14d"
                             *         ],
                             *         "settings": {
                             *           "publicKey": "HBOoWQWTTFlN1CyPL-wzf-0S28Ae7D4E23f6GL9FaXw",
                             *           "fingerprint": "random",
                             *           "serverName": "",
                             *           "spiderX": "/"
                             *         }
                             *       },
                             *       "tcpSettings": {
                             *         "acceptProxyProtocol": false,
                             *         "header": {
                             *           "type": "none"
                             *         }
                             *       }
                             *     } */
                            streamSettings?: string;
                            /** @example inbound-38476 */
                            tag?: string;
                            /** @example 0 */
                            total?: number;
                            /** @example 0 */
                            up?: number;
                        } | null;
                        /** @example true */
                        success?: boolean;
                    };
                };
            };
        };
    };
    clientTrafficsWithEmail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                email: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful / Failed */
            200: {
                headers: {
                    "Content-Encoding"?: string;
                    "Content-Length"?: string;
                    Date?: string;
                    Vary?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example  */
                        msg?: string;
                        obj?: {
                            /** @example 0 */
                            down?: number;
                            /** @example s729v2km */
                            email?: string;
                            /** @example true */
                            enable?: boolean;
                            /** @example 0 */
                            expiryTime?: number;
                            /** @example 4 */
                            id?: number;
                            /** @example 4 */
                            inboundId?: number;
                            /** @example 0 */
                            reset?: number;
                            /** @example 0 */
                            total?: number;
                            /** @example 0 */
                            up?: number;
                        } | null;
                        /** @example true */
                        success?: boolean;
                    };
                };
            };
        };
    };
    clientTrafficsWithId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful / Failed */
            200: {
                headers: {
                    "Content-Encoding"?: string;
                    "Content-Length"?: string;
                    Date?: string;
                    Vary?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example  */
                        msg?: string;
                        /** @example [
                         *       {
                         *         "down": 0,
                         *         "email": "s729v2km",
                         *         "enable": true,
                         *         "expiryTime": 0,
                         *         "id": 4,
                         *         "inboundId": 4,
                         *         "reset": 0,
                         *         "total": 0,
                         *         "up": 0
                         *       }
                         *     ] */
                        obj?: {
                            /** @example 0 */
                            down?: number;
                            /** @example s729v2km */
                            email?: string;
                            /** @example true */
                            enable?: boolean;
                            /** @example 0 */
                            expiryTime?: number;
                            /** @example 4 */
                            id?: number;
                            /** @example 4 */
                            inboundId?: number;
                            /** @example 0 */
                            reset?: number;
                            /** @example 0 */
                            total?: number;
                            /** @example 0 */
                            up?: number;
                        }[];
                        /** @example true */
                        success?: boolean;
                    };
                };
            };
        };
    };
    tgbotSendsBackupToAdmins: {
        parameters: {
            query?: never;
            header?: {
                ""?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    clientIpAddress: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                email: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response */
            200: {
                headers: {
                    "Content-Encoding"?: string;
                    "Content-Length"?: string;
                    Date?: string;
                    Vary?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example  */
                        msg?: string;
                        /** @example No IP Record */
                        obj?: string;
                        /** @example true */
                        success?: boolean;
                    };
                };
            };
        };
    };
    addInbound: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @example {"strategy": "always","refresh": 5,"concurrency": 3} */
                    allocate?: string;
                    /** @example 0 */
                    down?: number;
                    /** @example true */
                    enable?: boolean;
                    /** @example 0 */
                    expiryTime?: number;
                    /** @example  */
                    listen?: string;
                    /** @example 55421 */
                    port?: number;
                    /** @example vless */
                    protocol?: string;
                    /** @example New */
                    remark?: string;
                    /** @example {"clients": [{"id": "b86c0cdc-8a02-4da4-8693-72ba27005587","flow": "","email": "nt3wz904","limitIp": 0,"totalGB": 0,"expiryTime": 0,"enable": true,"tgId": "","subId": "rqv5zw1ydutamcp0","reset": 0}],"decryption": "none","fallbacks": []} */
                    settings?: string;
                    /** @example {"enabled": true,"destOverride": ["http","tls","quic","fakedns"],"metadataOnly": false,"routeOnly": false} */
                    sniffing?: string;
                    /** @example {"network": "tcp","security": "reality","externalProxy": [],"realitySettings": {"show": false,"xver": 0,"dest": "yahoo.com:443","serverNames": ["yahoo.com","www.yahoo.com"],"privateKey": "wIc7zBUiTXBGxM7S7wl0nCZ663OAvzTDNqS7-bsxV3A","minClient": "","maxClient": "","maxTimediff": 0,"shortIds": ["47595474","7a5e30","810c1efd750030e8","99","9c19c134b8","35fd","2409c639a707b4","c98fc6b39f45"],"settings": {"publicKey": "2UqLjQFhlvLcY7VzaKRotIDQFOgAJe1dYD1njigp9wk","fingerprint": "random","serverName": "","spiderX": "/"}},"tcpSettings": {"acceptProxyProtocol": false,"header": {"type": "none"}}} */
                    streamSettings?: string;
                    /** @example 0 */
                    total?: number;
                    /** @example 0 */
                    up?: number;
                };
            };
        };
        responses: {
            /** @description Successful / Failed */
            200: {
                headers: {
                    "Content-Encoding"?: string;
                    "Content-Length"?: string;
                    Date?: string;
                    Vary?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Create Successfully */
                        msg?: string;
                        obj?: {
                            /** @example {"strategy": "always","refresh": 5,"concurrency": 3} */
                            allocate?: string;
                            /** @example null */
                            clientStats?: unknown;
                            /** @example 0 */
                            down?: number;
                            /** @example true */
                            enable?: boolean;
                            /** @example 0 */
                            expiryTime?: number;
                            /** @example 5 */
                            id?: number;
                            /** @example  */
                            listen?: string;
                            /** @example 55421 */
                            port?: number;
                            /** @example vless */
                            protocol?: string;
                            /** @example New */
                            remark?: string;
                            /** @example {"clients": [{"id": "b86c0cdc-8a02-4da4-8693-72ba27005587","flow": "","email": "nt3wz904","limitIp": 0,"totalGB": 0,"expiryTime": 0,"enable": true,"tgId": "","subId": "rqv5zw1ydutamcp0","reset": 0}],"decryption": "none","fallbacks": []} */
                            settings?: string;
                            /** @example {"enabled": true,"destOverride": ["http","tls","quic","fakedns"],"metadataOnly": false,"routeOnly": false} */
                            sniffing?: string;
                            /** @example {"network": "tcp","security": "reality","externalProxy": [],"realitySettings": {"show": false,"xver": 0,"dest": "yahoo.com:443","serverNames": ["yahoo.com","www.yahoo.com"],"privateKey": "wIc7zBUiTXBGxM7S7wl0nCZ663OAvzTDNqS7-bsxV3A","minClient": "","maxClient": "","maxTimediff": 0,"shortIds": ["47595474","7a5e30","810c1efd750030e8","99","9c19c134b8","35fd","2409c639a707b4","c98fc6b39f45"],"settings": {"publicKey": "2UqLjQFhlvLcY7VzaKRotIDQFOgAJe1dYD1njigp9wk","fingerprint": "random","serverName": "","spiderX": "/"}},"tcpSettings": {"acceptProxyProtocol": false,"header": {"type": "none"}}} */
                            streamSettings?: string;
                            /** @example inbound-55421 */
                            tag?: string;
                            /** @example 0 */
                            total?: number;
                            /** @example 0 */
                            up?: number;
                        };
                        /** @example true */
                        success?: boolean;
                    };
                };
            };
        };
    };
    addClientToInbound: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @example 5 */
                    id?: number;
                    /** @example {"clients": [{"id": "bbfad557-28f2-47e5-9f3d-e3c7f532fbda","flow": "","email": "dp1plmlt8","limitIp": 0,"totalGB": 0,"expiryTime": 0,"enable": true,"tgId": "","subId": "2rv0gb458kbfl532","reset": 0}]} */
                    settings?: string;
                };
            };
        };
        responses: {
            /** @description Successful / Failed */
            200: {
                headers: {
                    "Content-Encoding"?: string;
                    "Content-Length"?: string;
                    Date?: string;
                    Vary?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Client(s) added Successfully */
                        msg?: string;
                        /** @example null */
                        obj?: unknown;
                        /** @example true */
                        success?: boolean;
                    };
                };
            };
        };
    };
    updateInbound: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                inboundId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @example {
                     *       "strategy": "always",
                     *       "refresh": 5,
                     *       "concurrency": 3
                     *     } */
                    allocate?: string;
                    /** @example 0 */
                    down?: number;
                    /** @example true */
                    enable?: boolean;
                    /** @example 0 */
                    expiryTime?: number;
                    /** @example  */
                    listen?: string;
                    /** @example 44322 */
                    port?: number;
                    /** @example vless */
                    protocol?: string;
                    /** @example  */
                    remark?: string;
                    /** @example {
                     *       "clients": [
                     *         {
                     *           "id": "a39c9655-bcbb-43c4-9b3b-ebd8b7ae9e1e",
                     *           "flow": "",
                     *           "email": "s729v2km",
                     *           "limitIp": 0,
                     *           "totalGB": 0,
                     *           "expiryTime": 0,
                     *           "enable": true,
                     *           "tgId": "",
                     *           "subId": "n2b9ubaioe06cak8",
                     *           "reset": 0
                     *         }
                     *       ],
                     *       "decryption": "none",
                     *       "fallbacks": []
                     *     } */
                    settings?: string;
                    /** @example {
                     *       "enabled": false,
                     *       "destOverride": [
                     *         "http",
                     *         "tls",
                     *         "quic",
                     *         "fakedns"
                     *       ],
                     *       "metadataOnly": false,
                     *       "routeOnly": false
                     *     } */
                    sniffing?: string;
                    /** @example {
                     *       "network": "tcp",
                     *       "security": "none",
                     *       "externalProxy": [],
                     *       "tcpSettings": {
                     *         "acceptProxyProtocol": false,
                     *         "header": {
                     *           "type": "none"
                     *         }
                     *       }
                     *     } */
                    streamSettings?: string;
                    /** @example 0 */
                    total?: number;
                    /** @example 0 */
                    up?: number;
                };
            };
        };
        responses: {
            /** @description Successful / Failed */
            200: {
                headers: {
                    "Content-Encoding"?: string;
                    "Content-Length"?: string;
                    Date?: string;
                    Vary?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Update Successfully */
                        msg?: string;
                        obj?: {
                            /** @example {
                             *       "strategy": "always",
                             *       "refresh": 5,
                             *       "concurrency": 3
                             *     } */
                            allocate?: string;
                            /** @example null */
                            clientStats?: unknown;
                            /** @example 0 */
                            down?: number;
                            /** @example true */
                            enable?: boolean;
                            /** @example 0 */
                            expiryTime?: number;
                            /** @example 4 */
                            id?: number;
                            /** @example  */
                            listen?: string;
                            /** @example 44360 */
                            port?: number;
                            /** @example vless */
                            protocol?: string;
                            /** @example  */
                            remark?: string;
                            /** @example {
                             *       "clients": [
                             *         {
                             *           "id": "a39c9655-bcbb-43c4-9b3b-ebd8b7ae9e1e",
                             *           "flow": "",
                             *           "email": "s729v2km",
                             *           "limitIp": 0,
                             *           "totalGB": 0,
                             *           "expiryTime": 0,
                             *           "enable": true,
                             *           "tgId": "",
                             *           "subId": "n2b9ubaioe06cak8",
                             *           "reset": 0
                             *         }
                             *       ],
                             *       "decryption": "none",
                             *       "fallbacks": []
                             *     } */
                            settings?: string;
                            /** @example {
                             *       "enabled": false,
                             *       "destOverride": [
                             *         "http",
                             *         "tls",
                             *         "quic",
                             *         "fakedns"
                             *       ],
                             *       "metadataOnly": false,
                             *       "routeOnly": false
                             *     } */
                            sniffing?: string;
                            /** @example {
                             *       "network": "tcp",
                             *       "security": "none",
                             *       "externalProxy": [],
                             *       "tcpSettings": {
                             *         "acceptProxyProtocol": false,
                             *         "header": {
                             *           "type": "none"
                             *         }
                             *       }
                             *     } */
                            streamSettings?: string;
                            /** @example  */
                            tag?: string;
                            /** @example 0 */
                            total?: number;
                            /** @example 0 */
                            up?: number;
                        };
                        /** @example true */
                        success?: boolean;
                    };
                };
            };
        };
    };
    updateClient: {
        parameters: {
            query?: never;
            header?: {
                cookie?: string;
            };
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @example 3 */
                    id?: number;
                    /** @example {"clients":[{"id":"95e4e7bb-7796-47e7-e8a7-f4055194f776","alterId":0,"email":"test123","limitIp":2,"totalGB":42949672960,"expiryTime":1682864675944,"enable":true,"tgId":"","subId":""}]} */
                    settings?: string;
                };
            };
        };
        responses: {
            /** @description Successful / Failed */
            200: {
                headers: {
                    "Content-Encoding"?: string;
                    "Content-Length"?: string;
                    Date?: string;
                    Vary?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Client updated Successfully */
                        msg?: string;
                        /** @example null */
                        obj?: unknown;
                        /** @example true */
                        success?: boolean;
                    };
                };
            };
        };
    };
    clearClientIpAddress: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                email: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response */
            200: {
                headers: {
                    "Content-Encoding"?: string;
                    "Content-Length"?: string;
                    Date?: string;
                    Vary?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Log Cleared Successfully */
                        msg?: string;
                        /** @example null */
                        obj?: unknown;
                        /** @example true */
                        success?: boolean;
                    };
                };
            };
        };
    };
    resetTrafficsOfAllInbounds: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response */
            200: {
                headers: {
                    "Content-Encoding"?: string;
                    "Content-Length"?: string;
                    Date?: string;
                    Vary?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example all traffic has been reset Successfully */
                        msg?: string;
                        /** @example null */
                        obj?: unknown;
                        /** @example true */
                        success?: boolean;
                    };
                };
            };
        };
    };
    resetTrafficsOfAllClientsInAnInbound: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                inboundId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response */
            200: {
                headers: {
                    "Content-Encoding"?: string;
                    "Content-Length"?: string;
                    Date?: string;
                    Vary?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example All traffic from the client has been reset. Successfully */
                        msg?: string;
                        /** @example null */
                        obj?: unknown;
                        /** @example true */
                        success?: boolean;
                    };
                };
            };
        };
    };
    resetClientTraffic: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                inboundId: string;
                email: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response */
            200: {
                headers: {
                    "Content-Encoding"?: string;
                    "Content-Length"?: string;
                    Date?: string;
                    Vary?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Traffic has been reset Successfully */
                        msg?: string;
                        /** @example null */
                        obj?: unknown;
                        /** @example true */
                        success?: boolean;
                    };
                };
            };
        };
    };
    deleteClient: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                inboundId: string;
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful / Failed */
            200: {
                headers: {
                    "Content-Encoding"?: string;
                    "Content-Length"?: string;
                    Date?: string;
                    Vary?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Client deleted Successfully */
                        msg?: string;
                        /** @example null */
                        obj?: unknown;
                        /** @example true */
                        success?: boolean;
                    };
                };
            };
        };
    };
    deleteInbound: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                inboundId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful / Failed */
            200: {
                headers: {
                    "Content-Encoding"?: string;
                    "Content-Length"?: string;
                    Date?: string;
                    Vary?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Delete Successfully */
                        msg?: string;
                        /** @example 3 */
                        obj?: number;
                        /** @example true */
                        success?: boolean;
                    };
                };
            };
        };
    };
    deleteDepletedClients: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                inboundId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response */
            200: {
                headers: {
                    "Content-Encoding"?: string;
                    "Content-Length"?: string;
                    Date?: string;
                    Vary?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example All depleted clients are deleted Successfully */
                        msg?: string;
                        /** @example null */
                        obj?: unknown;
                        /** @example true */
                        success?: boolean;
                    };
                };
            };
        };
    };
    onlineClients: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": Record<string, never>;
            };
        };
        responses: {
            /** @description Response */
            200: {
                headers: {
                    "Content-Encoding"?: string;
                    "Content-Length"?: string;
                    Date?: string;
                    Vary?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example  */
                        msg?: string;
                        /** @example [
                         *       "88vzckui"
                         *     ] */
                        obj?: string[];
                        /** @example true */
                        success?: boolean;
                    };
                };
            };
        };
    };
}
