// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv cloudflare-env.d.ts`

interface CloudflareEnv {
	ADMIN_USERNAME: string;
	ADMIN_PASSWORD: string;
	JWT_SECRET: string;
	SESSION_TAG: string;
	SESSION_DURATION: string;
	DB: D1Database;
	ASSETS: Fetcher;
}
